Traceback (most recent call last):
  File "D:\Code\Project\PycharmWorkspaces\PycharmMisc\django-volt-dashboard-master\media\task\scripts\69_task.py", line 19, in <module>
    df = pd.read_csv('../../heart.csv')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Code\Environment\Anaconda\Lib\site-packages\pandas\util\_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Code\Environment\Anaconda\Lib\site-packages\pandas\util\_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Code\Environment\Anaconda\Lib\site-packages\pandas\io\parsers\readers.py", line 950, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Code\Environment\Anaconda\Lib\site-packages\pandas\io\parsers\readers.py", line 605, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Code\Environment\Anaconda\Lib\site-packages\pandas\io\parsers\readers.py", line 1442, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Code\Environment\Anaconda\Lib\site-packages\pandas\io\parsers\readers.py", line 1735, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "D:\Code\Environment\Anaconda\Lib\site-packages\pandas\io\common.py", line 856, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '../../heart.csv'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Code\Project\PycharmWorkspaces\PycharmMisc\django-volt-dashboard-master\media\task\scripts\69_task.py", line 21, in <module>
    df = pd.read_excel('../../heart.csv')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Code\Environment\Anaconda\Lib\site-packages\pandas\util\_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Code\Environment\Anaconda\Lib\site-packages\pandas\util\_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Code\Environment\Anaconda\Lib\site-packages\pandas\io\excel\_base.py", line 482, in read_excel
    io = ExcelFile(io, storage_options=storage_options, engine=engine)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Code\Environment\Anaconda\Lib\site-packages\pandas\io\excel\_base.py", line 1652, in __init__
    ext = inspect_excel_format(
          ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Code\Environment\Anaconda\Lib\site-packages\pandas\io\excel\_base.py", line 1525, in inspect_excel_format
    with get_handle(
         ^^^^^^^^^^^
  File "D:\Code\Environment\Anaconda\Lib\site-packages\pandas\io\common.py", line 865, in get_handle
    handle = open(handle, ioargs.mode)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '../../heart.csv'
